version: '3'

services:

  fast.coach.api:
    build: .
    depends_on:
      - postgres-db
    volumes:
      - ./:/usr/src/app:ro
    command:  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    ports:
      - 8000:8000
    
    env_file:
      - ./.env
    
    environment:

      - DATABASE_HOST = localhost
      - DATABASE_PASSWORD = anselmo
      - DATABASE_NAME = fast-coach-db
      - DATABASE_USERNAME = postgres
      - DATABASE_PORT=8000

      - ALGORITHM = HS256
      - SECRET_KEY =  09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ACCESS_TOKEN_EXPIRATION_TIME = 1440

      - AFRICAS_TALKING_API_KEY = 5385dfb553bd3ad9d181a3b87f04f5ee307ef84a776f294eeef34609b900a658
      - AFRICAS_TALKING_ENV = sandbox
      - SENDER_CODE = 1795
 
  
  postgres-db:
    image: postgres
    
    environment:
      - POSTGRES_PASSWORD=anselmo
      - POSTGRES_DB=fast-coach-db
    volumes:
      - postgres-db-v:/var/lib/postgresql/data

volumes:
  postgres-db-v:
    